version: "3.9"
services:

# Jaeger Tracing Service - https://www.jaegertracing.io/docs/1.26/
  jaeger:
    image: jaegertracing/all-in-one:1.26
    ports:
      - 5775:5775/udp # zipkin.thrift compact protocol
      - 6831:6831/udp # jaeger.thrift compact protocol
      - 6832:6832/udp # jaeger.thrift binary
      - 5778:5778     # serve configs
      - 16686:16686   # frontend
      - 14268:14268   # accept jaeger.thrift from clients
      - 14250:14250   # accept model.proto
      - 9411:9411     # zipkin compatible endpoint
    environment: 
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"

# OpenTelemetry Collector - https://opentelemetry.io/docs/collector/
# The collector acts as a single endpoint for all services to send telemetry data to
# The collector can forward that data to multiple backend services like Jaeger, Prometheus, etc...
# The collector helps keep application code *simple* in terms of telemetry.
  otelcollector:
    image: otel/opentelemetry-collector:latest
    command: --config=/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    volumes:
      - /mnt/c/Users/jakev/Documents/code/telemetry-demo/telemetry_demo/collector_config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on: 
      - jaeger

# Just sends a message to the collector with key "foo"
  sender:
    build:
      context: .
      dockerfile: dockerfiles/service1.dockerfile
    image: service1:local
    depends_on:
      - otelcollector

# Just sends a message to the collector with the key "bar"
  sender2:
    build:
      context: .
      dockerfile: dockerfiles/service2.dockerfile
    image: service2.local
    depends_on: 
      - otelcollector

# A flask app that sends a message to the collector.
# Try http://localhost:5000/add/10/5
# Then open Jaeger and search for traces from the flask-app service
  flaskapp:
    build:
      context: .
      dockerfile: dockerfiles/flask.dockerfile
    image: otelflaskapp:local
    depends_on:
      - otelcollector
    ports:
      - 5000:5000