# Move this file to /tmp/otel-collector-config.yaml
receivers:
    otlp:
        protocols:
            grpc:
            http:

exporters:
    logging:
        loglevel: debug
    jaeger:
        endpoint: "jaeger:14250"
        insecure: true

processors:
    batch:
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [logging, jaeger]
            processors: [batch]